#!/bin/sh

# debug runmode gives unwanted output
unset PB_RUNMODE

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="sweep_group"
N_TEST=9

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    echo "*** running $N_TEST tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

POST_CMD="rm -f"
if [ "$1" = "-k" ] ; then
    # -k: keep the output files
    POST_CMD="touch"
fi

rm -f *.out *.log

if ! $PB setup -d ${TEST_NAME}_exp.xml >test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

for inp_file in `ls input/*.dat` ; do
    if ! $PB input -d ${TEST_NAME}_inp.xml $inp_file >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not import $inp_file. See test.log"
	exit 1
    fi
done

rc=0
t=1
while [ $t -le $N_TEST ] ; do
    echo "  test "$t
    CMD="$PB query -d ${TEST_NAME}_qry_${t}.xml"
    if ! $CMD >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not perform query (see test.log)"
	echo "   $CMD"
	rc=`expr $rc + 1`
    else
	# some tests create multiple output files
	cat ${TEST_NAME}_${t}*.gp > ${TEST_NAME}_${t}.out
	if [ -n "$VERIFY" ] ; then
	    if ! diff ${TEST_NAME}_${t}.out verify/test_${t}.vfy ; then
		echo "#* ERROR in ${TEST_NAME}, test $t: query returned wrong data"
		echo "   (file ${TEST_NAME}_${t}.out vs. verify/test_${t}.vfy)"
		rc=`expr $rc + 1`
	    else
		$POST_CMD ${TEST_NAME}_${t}*.ps ${TEST_NAME}_${t}*.gp
	    fi
            rm -f *.out
	else	
	    mv ${TEST_NAME}_${t}.out verify/test_${t}.vfy
	    $POST_CMD ${TEST_NAME}_${t}*.ps ${TEST_NAME}_${t}*.gp 
	fi
    fi
    t=`expr $t + 1`
done


if  [ -z "$PB_RUNMODE" ] ; then 
    # make sure the database server will be able to delete the database
    sleep 2
    if ! $PB delete -e ${TEST_NAME}_TEST --dontask >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
	exit 1
    fi
fi

if [ $rc = 0 ] ; then
    rm -f test.log 
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
