#!/bin/sh

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="plottype"
N_TEST=1

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    echo "*** running $N_TEST tests in '${TEST_NAME}'"
fi
export PB_RUNMODE=debug
rm -f *.out *.log

if ! $PB setup -d ${TEST_NAME}_exp.xml >test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

for d in 1 10 ; do
	if ! $PB input -d ${TEST_NAME}_inp.xml data_T${d}.dat >>test.log 2>&1; then
    		echo "#* ERROR in ${TEST_NAME}: could not import data_T${d}.dat. See test.log"
		exit 1
	fi
done

rc=0
t=1
while [ $t -le $N_TEST ] ; do
	echo "  test "$t
	if ! $PB query -d ${TEST_NAME}_qry.xml >> test.log 2>&1; then
	    echo "#* ERROR in ${TEST_NAME}: could not perform query (see test.log)"
	    echo "   $PB query -d ${TEST_NAME}_qry.xml"
	    rc=`expr $rc + 1`
	else
	    if [ -n "$VERIFY" ] ; then
		if ! diff ${TEST_NAME}.gp verify/test_$t.vfy ; then
		    echo "#* ERROR in ${TEST_NAME}, test $t: query returned wrong data"
		    echo "   (file ${TEST_NAME}.gp vs. verify/test_$t.vfy)"
		    rc=`expr $rc + 1`
		else
		    rm ${TEST_NAME}.gp ${TEST_NAME}.eps
		fi
	    else
		mv ${TEST_NAME}.gp verify/test_$t.vfy
		rm ${TEST_NAME}.eps		
	    fi
	fi
	
	t=`expr $t + 1`
done

# make sure the database server will be able to delete the database
sleep 2

if ! $PB delete -e ${TEST_NAME}_TEST --dontask >>test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
    exit 1
fi

if [ $rc = 0 ] ; then
    rm test.log
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
