#!/bin/sh

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="filename"
unset PB_RUNMODE

inp=("bench_N_proc_1.dat" "data_Nproc1.dat" "bench_nproc1.dat" "bench_nproc1.dat"
    "bench_nproc1.dat" "bench_nproc1.dat" "bench_UFSN_proc1.dat" "bench_ufs_N_proc1.dat")
desc=("1" "1" "4" "4" "2" "2" "3" "3")
args=("-t -u" "-t -u" "-t" "-u -t" "-t -f fs=UFS" "-t -f fs=ABC" "-t" "-t")
pb_rc=( 0 0 1 0 0 1 0 1)

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    TEST_OUTPUT=verify/test_@.vfy
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    TEST_OUTPUT=test_@.out
    echo "*** running ${#inp[@]} tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

rm -f *.out *.log

# setup 
if ! $PB setup -d ${TEST_NAME}_exp.xml >>test.log 2>&1 ; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

# import data  - this is the test!
rc=0
for (( i = 0 ; i < ${#inp[@]} ; i++ )) ; do
    t=`expr $i + 1`
    echo "  test "$t
    INPUT_ARGS="${args[$i]} -d ${TEST_NAME}_inp_${desc[$i]}.xml input/${inp[$i]}"
    INPUT_OUT=`echo $TEST_OUTPUT | sed s/@/$t/`
    $PB input $INPUT_ARGS > $INPUT_OUT
    test_rc=$?
    if [ $test_rc != ${pb_rc[$i]} ]; then
	echo $test_rc ${pb_rc[$i]}
	echo "#* ERROR in ${TEST_NAME}: could not perform input $t:"
	echo "   $PB input $INPUT_ARGS"
	echo "   (see file $INPUT_OUT)"
	rc=`expr $rc + 1`
    elif [ -n "$VERIFY" ] ; then
	if ! diff test_$t.out verify/test_$t.vfy ; then
	    echo "#* ERROR in ${TEST_NAME}: query $t returned wrong data "
	    echo "   $PB input $INPUT_ARGS"
	    echo "   (file test_$t.out vs. verify/test_$t.vfy)"
	    rc=`expr $rc + 1`
	else
	    rm -f $INPUT_OUT
	fi
    fi
done

# clean up
if ! $PB delete -e ${TEST_NAME}_TEST --dontask  >>test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
    exit 1
fi

if [ $rc = 0 ] ; then
    rm -f test.log *.err
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
