#!/bin/sh

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="xml"
N_TESTS=3

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    TEST_OUTPUT=verify/test_@.vfy
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    TEST_OUTPUT=test_@.out
    echo "*** running $N_TESTS tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

rm -f *.out *.log

# setup 
if ! $PB setup -d ${TEST_NAME}_exp.xml >>test.log 2>&1 ; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

# import data
if ! $PB input -d ${TEST_NAME}_inp.xml input/*.dat >>test.log 2>&1 ; then
    echo "#* ERROR in ${TEST_NAME}: could not import data. See test.log"
    exit 1
fi

# query data
rc=0
t=0
for i in 1 2 3 ; do
    t=`expr $t + 1`
    echo "  test "$t
    QUERY_ARGS="-d ${TEST_NAME}_qry_$i.xml"
    QUERY_OUT=`echo $TEST_OUTPUT | sed s/@/$t/`
    if ! $PB query $QUERY_ARGS > $QUERY_OUT ; then
        echo "#* ERROR in ${TEST_NAME}: could not perform query $t:"
        echo "   $PB query $QUERY_ARGS"
        echo "   (see file $QUERY_OUT)"
        rc=`expr $rc + 1`
    elif [ -n "$VERIFY" ] ; then
        if ! diff test_$t.out verify/test_$t.vfy ; then
            echo "#* ERROR in ${TEST_NAME}: query $t returned wrong data "
            echo "   $PB query $QUERY_ARGS"
            echo "   (file test_$t.out vs. verify/test_$t.vfy)"
            rc=`expr $rc + 1`
        else
            rm -f $QUERY_OUT
        fi
    fi    
done

# clean up
sleep 2
if ! $PB delete -e ${TEST_NAME}_TEST --dontask  >>test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
    exit 1
fi

if [ $rc = 0 ] ; then
    rm -f test.log *.err test.xml
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
