#!/bin/sh

# debug runmode gives unwanted output
unset PB_RUNMODE

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="marker"

expected_rc=( 0 0 0 1 0 0 0 0 0 0 0 0 0)
input_args=( '-u' '-u' '-u' '-u' '-f int=0 -f string="text"' '-u' '-u' '-u' '-u' '-u' '-u' '-u' '-u')
run_ids=( 1 2 3 4 5 6 7 8 9 10 11 12 13)
N_TEST=`expr ${#run_ids[@]} + ${#expected_rc[@]}`
N_RUN=${#run_ids[@]}

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    echo "*** running $N_TEST tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

rm -f *.out *.log

# setup 
if ! $PB setup -d ${TEST_NAME}_exp.xml >>test.log 2>&1 ; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

# import data - we test the success of this via the 
rc=0
i=0
while [ $i -lt $N_RUN ] ; do
    t=`expr $i + 1`
    echo "  test "$t
    INP_ARGS="-d ${TEST_NAME}_inp_${t}.xml ${input_args[i]} input/input_${t}.dat"
    CMD="$PB input $INP_ARGS"
    $CMD > test_$t.out    
    if [ $? != ${expected_rc[$i]} ] ; then
	echo "#* ERROR in ${TEST_NAME}: unexpected return code for input operation:"
	echo "   $CMD"
	echo "   (see file test_$t.out)"
	rc=`expr $rc + 1`
    else
	if [ -n "$VERIFY" ] ; then
	    if ! diff test_$t.out verify/test_$t.vfy ; then
		echo "#* ERROR in ${TEST_NAME}: input $t had wrong ouput "
		echo "   $CMD"
		echo "   (file test_$t.out vs. verify/test_$t.vfy)"
		rc=`expr $rc + 1`
	    else
		rm -f test_$t.out
	    fi
	else
	    mv test_$t.out verify/test_$t.vfy
	fi
    fi
    i=`expr $i + 1`
done

# do the queries to verify that the correct data was imported
i=0
while [ $i -lt $N_RUN ] ; do
    t=`expr $i + 1 + $N_RUN`
    echo "  test "$t

    QUERY_ARGS="-d ${TEST_NAME}_qry_1.xml -f f.runid=${run_ids[$i]}"
    
    $PB query $QUERY_ARGS > test_$t.out 
    if [ $? != ${expected_rc[$i]} ] ; then
	echo "#* ERROR in ${TEST_NAME}: unexpected return code for input operation:"
	echo "   $CMD"
	echo "   (see file test_$t.out)"
	rc=`expr $rc + 1`
    else
	if [ -n "$VERIFY" ] ; then
	    if ! diff test_$t.out verify/test_$t.vfy ; then
		echo "#* ERROR in ${TEST_NAME}: query $t returned wrong data "
		echo "   $PB query $QUERY_ARGS"
		echo "   (file test_$t.out vs. verify/test_$t.vfy)"
		rc=`expr $rc + 1`
	    else
		rm -f test_$t.out
	    fi
	else
	    mv test_$t.out verify/test_$t.vfy
	fi
    fi
    i=`expr $i + 1`
done

# make sure the database server will be able to delete the database
sleep 2

# clean up if not in debug mode
if [ -z "$PB_RUNMODE" ] ; then
    if ! $PB delete -e ${TEST_NAME}_TEST --dontask  >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
	exit 1
    fi
fi

if [ $rc = 0 ] ; then
    rm -f test.log *.err
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
