#!/bin/sh

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="plain_table"
N_TEST=2

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    TEST_OUTPUT=verify/test_@.vfy
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    TEST_OUTPUT=test_@.out
    echo "*** running $N_TEST tests in '${TEST_NAME}'"
fi

rm -f *.out *.log

# setup 
if ! $PB setup -d ${TEST_NAME}_exp.xml >>test.log 2>&1 ; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

# import data - this is the test!
rc=0
t=1
while [ $t -le $N_TEST ] ; do
    echo "  test "$t

    INPUT_ARGS="-t -d ${TEST_NAME}_inp.xml latency_${t}.dat"
    INPUT_OUT=`echo $TEST_OUTPUT | sed s/@/$t/`
    if ! $PB input $INPUT_ARGS > $INPUT_OUT 2>&1 ; then
	echo "#* ERROR in ${TEST_NAME}: could not import latency${t}.dat."
	exit 1
    elif [ -n "$VERIFY" ] ; then
	if ! diff test_$t.out verify/test_$t.vfy ; then
	    echo "#* ERROR in ${TEST_NAME}: query $t returned wrong data "
	    echo "   $PB input $INPUT_ARGS"
	    echo "   (file test_$t.out vs. verify/test_$t.vfy)"
	    rc=`expr $rc + 1`
	else
	    rm -f $INPUT_OUT
	fi
    fi

    t=`expr $t + 1`
done

# clean up
if ! $PB delete -e ${TEST_NAME}_TEST --dontask  >>test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
    exit 1
fi

if [ $rc = 0 ] ; then
    rm -f test.log *.err
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
