#!/bin/sh

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
unset PB_RUNMODE

TEST_NAME="regexp2"
N_TEST=3
pb_rc=( 0 0 1 )

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    echo "*** running $N_TEST tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

rm -f *.out *.log

if ! $PB setup -d ${TEST_NAME}_exp.xml >test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

rc=0

if ! $PB input -u -d ${TEST_NAME}_inp.xml input/*.dat >>test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not import data. See test.log"
    exit 1
fi

i=0
t=1
for qry_idx in 1 2 3 ; do
    echo "  test "$t
    CMD="$PB query -d ${TEST_NAME}_qry_${qry_idx}.xml"
    $CMD > test_${t}.out 2>>test.log
    test_rc=$?
    if [ $test_rc != ${pb_rc[$i]} ]; then
	echo "#* ERROR in ${TEST_NAME}: query returned with unexpected return code:"
	echo "   $CMD"
	echo "   (see file test.log)"
	rc=`expr $rc + 1`
    else
	if [ -n "$VERIFY" ] ; then
	    if ! diff test_${t}.out verify/test_${t}.vfy ; then
		echo "#* ERROR in ${TEST_NAME}, test $t: query returned wrong data"
		echo "   $CMD"
		echo "   (file ${TEST_NAME}_${t}.gp vs. verify/test_${t}.vfy)"
		rc=`expr $rc + 1`
	    else
		rm test_${t}.out
	    fi
	else	
	    mv test_${t}.out verify/test_${t}.vfy
	fi
    fi
    t=`expr $t + 1`
    i=`expr $i + 1`
done


# clean up if not in debug mode
if [ -z "$PB_RUNMODE" ] ; then
    sleep 2
    if ! $PB delete -e ${TEST_NAME}_TEST --dontask >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
	exit 1
    fi
fi

if [ $rc = 0 ] ; then
    rm -f test.log 
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
