#!/bin/sh

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="split"
unset PB_RUNMODE

pb_rc=( 0 1 1 0 )

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    TEST_OUTPUT=verify/test_@.vfy
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    TEST_OUTPUT=test_@.out
    echo "*** running ${#pb_rc[@]} tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

rm -f *.out *.log

# setup 
if ! $PB setup -d ${TEST_NAME}_exp.xml >>test.log 2>&1 ; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

# import data  - this is the test!
rc=0
for (( i = 0 ; i < ${#pb_rc[@]} ; i++ )) ; do
    t=`expr $i + 1`
    echo "  test "$t
    ARGS="input -t -d ${TEST_NAME}_inp_1.xml input_${t}.dat"
    OUT=`echo $TEST_OUTPUT | sed s/@/$t/`
    $PB $ARGS > $OUT
    test_rc=$?
    if [ $test_rc != ${pb_rc[$i]} ]; then
	echo "#* ERROR in ${TEST_NAME}: could not perform input $t:"
	echo "   $PB $ARGS"
	echo "   (see file $OUT)"
	rc=`expr $rc + 1`
    elif [ -n "$VERIFY" ] ; then
	if ! diff test_$t.out verify/test_$t.vfy ; then
	    echo "#* ERROR in ${TEST_NAME}: import $t processed wrong data "
	    echo "   $PB $ARGS"
	    echo "   (file test_$t.out vs. verify/test_$t.vfy)"
	    rc=`expr $rc + 1`
	else
	    rm -f $OUT
	fi
    fi
done

# clean up
# clean up if not in debug mode
if [ -z "$PB_RUNMODE" ] ; then
    sleep 2
    if ! $PB delete -e ${TEST_NAME}_TEST --dontask  >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
	exit 1
    fi
fi

if [ $rc = 0 ] ; then
    rm -f test.log *.err
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
