#!/bin/sh

# debug runmode gives unwanted output
unset PB_RUNMODE

if [ -z "$PB" ] ; then
    PB=../../bin/perfbase
fi
TEST_NAME="multi_target"
N_TEST=1

if [ "$1" = "-c" ] ; then
    VERIFY=""    
    echo "*** re-creating verification data for '${TEST_NAME}'"
else
    VERIFY="yes"
    echo "*** running $N_TEST tests in '${TEST_NAME}'"
fi
if [ "$1" = "-d" ] ; then
    export PB_RUNMODE="debug"
fi

rm -f *.out *.log

if ! $PB setup -d ${TEST_NAME}_exp.xml >test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not setup experiment. See test.log"
    exit 1
fi

if ! $PB input -d ${TEST_NAME}_inp.xml input_*.dat >>test.log 2>&1; then
    echo "#* ERROR in ${TEST_NAME}: could not import input_*.dat. See test.log"
    exit 1
fi

t=1
rc=0
while [ $t -le $N_TEST ] ; do
    echo "  test "$t
    CMD="$PB query -d ${TEST_NAME}_qry_${t}.xml"
    if ! $CMD  >test_${t}.out 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not perform query (see test.log)"
	echo "   $CMD"
	rc=`expr $rc + 1`
    else
	if [ -n "$VERIFY" ] ; then
	    if ! diff test_${t}.out verify/test_${t}.vfy ; then
		echo "#* ERROR in ${TEST_NAME}, test $t: query returned wrong data"
		echo "   $CMD"
		echo "   (file ${TEST_NAME}_${t}.gp vs. verify/test_${t}.vfy)"
		rc=`expr $rc + 1`
	    else
		rm test_${t}.out
	    fi
	else	
	    mv test_${t}.out verify/test_${t}.vfy
	fi
    fi
    t=`expr $t + 1`
done


if [ -z "$PB_RUNMODE" ] ; then
    # make sure the database server will be able to delete the database
    sleep 2
    if ! $PB delete -e ${TEST_NAME}_TEST --dontask >>test.log 2>&1; then
	echo "#* ERROR in ${TEST_NAME}: could not delete experiment. See test.log"
	exit 1
    fi
fi

if [ $rc = 0 ] ; then
    rm test.log
fi

echo "*** done with tests in '${TEST_NAME}' ($rc failed)"

exit $rc
